##
## EPITECH PROJECT, 2022
## B-CPE-200-PAR-2-1-lemin-thomas.lebouc
## File description:
## Makefile
##

SILENT	=	@

MAK	=	$(SILENT)make -C

all:
	$(MAK) ./my

clean:
	$(MAK) ./my clean

fclean:
	$(MAK) ./my fclean

debug:
	$(MAK) ./my debug

re: fclean all

.PHONY: all clean fclean debug re
